일단 첫 대문페이지를 고쳤습니다.
elixir-korea/elixir-korea.github.io pull request #12
Opened 2019-12-25 06:36 UTC by seungjin

일단 세롬기본으로 나오는 페이지를 걷어내고, 
@nallwhy 님의 리드미 파일을 기본으로 무언가 정체성을 나타낸 대문페이지를 썻습니다. 
물론 추우에 대문페이지는 모임과 토의를 통해서 계속 다듬고 발전할것입니다. 
당장은 그냥 기본 템플릿만 보이는게 거슬러서 무언가라도 넣고 싶었습니다.
즐거운 성탄/년말 되세요.

2019-12-25 10:53 UTC, nallwhy reviewed
Elixir 의 번역을 엘릭서로 통일하는 것이 좋겠다는 의견입니다!

2019-12-25 11:01 UTC, Dalgona reviewed
"엘릭사"를 "엘릭서"로 변경하는 것에는 저도 동의합니다.

2019-12-25 11:01 UTC, Dalgona commented on pages/index.md
> +우리는 한국 개발자분들에게 보다 친근한 엘릭사 자료들을 서로 나눔으로서 엘릭사 프로그램 언어(Elixir Programming Language)의 저변확대에 도움이 되고자합니다. 이를 위해 엘릭사 관련 자료 나눔, 엘릭사 모임의 자료 정리, 자체적인 자료생산등을 합니다.
```suggestion
우리는 한국 개발자분들에게 보다 친근한 엘릭사 자료들을 서로 나눔으로써 [엘릭사 프로그램 언어(Elixir Programming Language)](https://elixir-lang.org)의 저변 확대에 도움이 되고자 합니다. 이를 위해 엘릭사 관련 자료 나눔, 엘릭사 모임의 자료 정리, 자체적인 자료 생산 등을 합니다.
```

2019-12-25 11:01 UTC, Dalgona commented on pages/index.md
> +
```suggestion
```

2019-12-25 11:01 UTC, Dalgona commented on pages/index.md
> +한국 엘릭사 유저그룹은 어떤형태로든지 모든분들의 참여를 환영합니다.
```suggestion
한국 엘릭사 사용자 모임은 어떤 형태로든지 모든 분들의 참여를 환영합니다.
```

2019-12-25 11:01 UTC, Dalgona commented on pages/index.md
> +그룹에 등록하신후에는 좀더 적극적인 참여가 가능해집니다.
```suggestion
그룹에 등록하신 후에는 좀더 적극적인 참여가 가능해집니다. 
```

2019-12-25 11:03 UTC, Dalgona commented
앗 타이밍이 안 맞아서 outdated된 버전에 댓글을 달았네요 ㅎㅎ... 💦

2019-12-25 11:28 UTC, 979156 commented
저도 엘릭서에 동의합니다!

2019-12-25 11:34 UTC, nallwhy requested changes

2019-12-25 11:34 UTC, nallwhy commented on pages/index.md
> +우리는 한국 개발자분들에게 보다 친근한 엘릭사 자료들을 서로 나눔으로써 [엘릭사 프로그램 언어(Elixir Programming Language)](https://elixir-lang.org)의 저변 확대에 도움이 되고자 합니다. 이를 위해 엘릭사 관련 자료 나눔, 엘릭사 모임의 자료 정리, 자체적인 자료 생산 등을 합니다.
```suggestion
우리는 한국 개발자분들에게 보다 친근한 엘릭서 자료들을 서로 나눔으로써 [엘릭서 프로그램 언어(Elixir Programming Language)](https://elixir-lang.org)의 저변 확대에 도움이 되고자 합니다. 이를 위해 엘릭서 관련 자료 나눔, 엘릭서 모임의 자료 정리, 자체적인 자료 생산 등을 합니다.
```

2019-12-25 11:34 UTC, nallwhy commented on serum.exs
> +  site_description: "한국 엘릭사 사용자 모임",
```suggestion
  site_description: "한국 엘릭서 사용자 모임",
```

2019-12-25 11:35 UTC, Dalgona commented on pages/index.md
> +우리는 한국 개발자분들에게 보다 친근한 엘릭사 자료들을 서로 나눔으로써 [엘릭사 프로그램 언어(Elixir Programming Language)](https://elixir-lang.org)의 저변 확대에 도움이 되고자 합니다. 이를 위해 엘릭사 관련 자료 나눔, 엘릭사 모임의 자료 정리, 자체적인 자료 생산 등을 합니다.
제가 outdated된 코드에 코멘트를 단 탓에 엘릭사가 되살아났습니다 ㅠㅠ

2019-12-25 12:03 UTC, seungjin commented on pages/index.md
> +우리는 한국 개발자분들에게 보다 친근한 엘릭사 자료들을 서로 나눔으로써 [엘릭사 프로그램 언어(Elixir Programming Language)](https://elixir-lang.org)의 저변 확대에 도움이 되고자 합니다. 이를 위해 엘릭사 관련 자료 나눔, 엘릭사 모임의 자료 정리, 자체적인 자료 생산 등을 합니다.
수정완료

2019-12-25 12:15 UTC, Dalgona approved these changes
👍👍👍

2019-12-25 12:16 UTC, nallwhy approved these changes

2019-12-25 12:17 UTC, merged

2019-12-26 01:46 UTC, jechol commented
용어 자리 잡히기 전에 엘릭서 -> 일릭서로 원어 발음대로 하는게 어떨까요?

(이미 자리 잡혀버린걸까요?)

2019-12-26 01:49 UTC, seungjin commented
모가 맞는지 진짜 잘 모르겠어요. 국립국어원에 물어봐야 할가요?
제 귀엔 "엘릭사"로 들립니다.

2019-12-26 01:54 UTC, jechol commented
온라인 영어 사전에는 https://en.dict.naver.com/#/entry/enko/426d115405b5492a86bf5b36dad7f238

elixir
Pronunciation	US∙UK [ ɪ|lɪksə(r) ] 

로 되어 있긴 합니다... 

근데 이미 이 언어 이전에, 클래시오브클랜 같은 게임에서 엘릭서로 사람들이 쓰고 있어서 그냥 써야겠네요...

2019-12-26 01:57 UTC, seungjin commented
프랑스어도 아니고, 영어는 내키는대로 쓰는 사람맘입니다. ㅋㅋㅋㅋ
이미 엘릭서로 쓰였다면 따르거나,, 아니면 내가 바꾸거나.ㅋㅋㅋ 둘중하나일듯.

2019-12-26 02:01 UTC, 979156 commented
@jechol님께서 올려주신 발음기호의 ə는 일반적으로 정확히는 아니지만 한글의 'ㅓ'에 대응 되는것으로 일고있습니다! Teacher의 경우에도 ˈtiːtʃə(r) 이구요!

2019-12-26 02:16 UTC, jechol commented
엘릭서가 원어민들이 쓰는 발음을 한글로 옮긴건 아니라는 점을 짚고 넘어가고 싶었습니다.
아무래도 현재 엘릭서 서울 밋업이 외국인들도 많고,
고치려면 아직 많이 쓰이는 곳이 없는 지금이 마지막 찬스 같아서요.

중요한 문제도 아니고 고치기에 번거로우면 
현재대로 엘릭서로 표기하도록 하죠.

2019-12-26 02:26 UTC, seungjin commented
Perl을 제가 "펄"이라고 말하면 처음에 알아듣는 외국인을 한번도 본적이 없었습니다.
P와 F발음 그리고 r과 l발음이 같이 섞인 저에겐 난제와도 같은 단어.. 

제가 Python/파이썬 이라고 발음하면 원어민 대부분의 경우 처음 발음이 P보단 F로 들리는데.. 아마 Fithon에 가까울듯.. 하지만 전후 구문의 맥락을 보고 Python이라고 이해하는거죠. 

외국어를 한국어로 쓴다는거 자체가 어려운 일이고 100% 매칭을 기대해서도 안되는 일인듯....
그리고 Elixir는 누 가모래도 제귀엔 "엘릭사"로 들립니다. ㅋㅋㅋㅋ 
가만보니 E와 I 그리고 L과 R 그리고 X까지.. 한국인에겐 어려운 발음이 많이 들어간 단어군요!!

2019-12-26 02:28 UTC, Dalgona commented
일단 여태까지 제 주변에서 "Elixir"를 "엘릭서" 이외의 방법으로 표기하는 걸 본 적이 없어서 저는 드릴 말씀이 없습니다. 💦 개인적인 느낌입니다만, 그 외의 표기는 많이 어색하네요 ㅎㅎ...

2019-12-26 02:37 UTC, jechol commented
python 처럼 기존에 있던 영단어를 이름으로 쓴다면
특별한 사정이 없는한 영어사전의 표기법대로 하는게 맞겠죠. (특히 언어 개발이 주로 이뤄진 미국식 발음)

어떤 표기가 옳냐 이전에, 
바꾸기에는 이미 널리 퍼졌다는 인식이 있는것 같네요.

엘릭서로 그냥 두시죠!

2020-01-04 04:48 UTC, nallwhy commented
elixir conf 영상 보면서 들어보니까
엘릭서와 엘릭사의 중간인거 같아서 ㅋㅋㅋㅋ

2020-01-06 03:55 UTC, jechol commented
와. jose valim 영상보니 아예 "엘" 이군요. GG