밋업(meetups) 카테고리(?) 생성
elixir-korea/elixir-korea.github.io pull request #18
Opened 2019-12-26 06:32 UTC by seungjin

테그기반으로 밋업 카테고리를 해더에 붙여 넣었습니다.

2019-12-29 04:43 UTC, nallwhy commented
meetup 을 정리한 결과를 post 에 올리는 것은 좋을 것 같은데, 공지 같은 경우에는 별도의 page 로 하는 것이 좋을 것 같다는 생각이 듭니다.

2019-12-29 06:39 UTC, seungjin commented
그럼 상단 카테고리가 
홈, 공지, 밋업, 포스트
이렇게 4개로 구성할가요?
모임에 대한 공지나 기타 공지는 공지로,, 밋업엔 밋업 발표자료위주..
그렇게 올리는것도 나쁘진 않다고 봅니다.

2020-01-01 17:06 UTC, nallwhy commented
아 Serum 에는 page 와 post 가 있는데요.
page 는 단순한 문서이고, post 는 태그도 있고 author 도 있고 그런 더 기능이 많은 문서입니다.
밋업 공지는 단순한 문서로 있는 것이 낫지 않을까 해서요!

2020-01-01 17:22 UTC, chulkilee commented on posts/2020-01-meetup-announce.md
> +케빈이 장소섭외를 예약중이라서 최종 결과가 결정되면 블러그와 밋업 사이트에 올리도록 하겠습니다.
블러그 -> 블로그 (표준국어대사전)

2020-01-01 17:23 UTC, chulkilee commented on posts/2020-01-meetup-announce.md
> +[2020년 1월 밋업 사이트 링크](https://www.meetup.com/Seoul-Elixir-Meetup/events/cvzblrybccbtb/)
한국에서 밋업을 어떻게 부르는지 모르겠는데.. 그냥 다음과 같이 링크를 걸어도 될 것 같습니다.

```
[2020년 1월 밋업](https://www.meetup.com/Seoul-Elixir-Meetup/events/cvzblrybccbtb/)
```

2020-01-01 17:25 UTC, chulkilee commented on includes/nav.html.eex
> +  <li><a href="<%= base "tags/announce" %>">Announces</a></li>
따로 "공지" 라는 카테고리는 필요 없을 것 같습니다. 모두 새소식이고.. 공지보다는 "소식" 에 가깝고, 사실 블로그 포스트 자체가 새소식을 다루는 것이니..

이 PR 에서는 빼는 것이 어떨까요?

2020-01-01 17:30 UTC, chulkilee commented on posts/2020-01-meetup-announce.md
> +tags: announce
PR 제목에 맞게 `meetup` 으로 바꿀까요?

그리고 perm link 포맷도 정해놓는게 편할 것 같습니다. 별도 이슈로 빼겠습니다.. #22

2020-01-06 17:22 UTC, chulkilee requested changes

2020-01-06 17:22 UTC, chulkilee commented on posts/2020-01-meetup-announce.md
> +케빈이 장소섭외를 예약중이라서 최종 결과가 결정되면 블로그와 밋업 사이트에 올리도록 하겠습니다.
https://www.meetup.com/Seoul-Elixir-Meetup/events/cvzblrybccbtb/

시간 장소가 확정된 것 같으니 업데이트 부탁드립니다!

2020-01-07 00:49 UTC, seungjin commented on posts/2020-01-meetup-announce.md
> +케빈이 장소섭외를 예약중이라서 최종 결과가 결정되면 블로그와 밋업 사이트에 올리도록 하겠습니다.
@nallwhy 님 그럼 확정된건가요? 확정되면 공지 업데이트 하고선  publish 하죠.

2020-01-09 22:48 UTC, nallwhy approved these changes

2020-01-10 00:33 UTC, Dalgona commented on posts/2020-01-meetup-announce.md
> +케빈이 장소섭외를 예약중이라서 최종 결과가 결정되면 블로그와 밋업 사이트에 올리도록 하겠습니다.
Approve 하셨으니 업데이트 하시면 될 것 같습니다. 👀

2020-01-10 02:59 UTC, seungjin commented
@chulkilee 장소업데이트 되었습니다. approve 부탁드립니다.

2020-01-10 06:40 UTC, chulkilee approved these changes

2020-01-10 06:41 UTC, merged