Add ga tag to head
elixir-korea/elixir-korea.github.io pull request #25
Opened 2020-01-06 15:06 UTC by nallwhy

2020-01-06 15:41 UTC, Dalgona approved these changes

2020-01-06 17:20 UTC, chulkilee requested changes

2020-01-06 17:20 UTC, chulkilee commented on includes/head-extras.html.eex
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155413685-1"></script>
어떤 구글 계정인가요? 개인 계정 소유가 아닌 모임의 계정이어야 한다고 봅니다.

2020-01-06 21:40 UTC, seungjin commented on includes/head-extras.html.eex
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155413685-1"></script>
네.. 아무래도 커뮤니티다 보니 정보의 투명성을 고려해야 한다고 봅니다. 
투명하지 못하게 할바에는 수집하지 않는게 차라리 후에 문제의 소지가 없다고 봅니다.

2020-01-06 21:41 UTC, seungjin requested changes
네.. 아무래도 커뮤니티다 보니 정보의 투명성을 고려해야 한다고 봅니다.
투명하지 못하게 할바에는 수집하지 않는게 차라리 후에 문제의 소지가 없다고 봅니다.

2020-01-06 23:21 UTC, nallwhy commented on includes/head-extras.html.eex
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155413685-1"></script>
GA 는 계정 소유의 개념이 없지 않나요?
필요한 분들 계정을 추가해드리면 동등한 것으로 알고 있습니다.

2020-01-07 00:16 UTC, chulkilee commented on includes/head-extras.html.eex
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155413685-1"></script>
#19 에서 논의 이어가지요!

2020-01-07 08:00 UTC, seungjin approved these changes

2020-01-11 04:57 UTC, chulkilee approved these changes

2020-01-11 10:39 UTC, merged