Add post 'Elixir 개발 환경을 설정해봅시다 (Mac)'
elixir-korea/elixir-korea.github.io pull request #44
Opened 2020-05-01 16:17 UTC by nallwhy

2020-05-01 21:57 UTC, Dalgona commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +# asdf
https://github.com/elixir-korea/elixir-korea.github.io/pull/21#discussion_r362347138

2020-05-01 22:01 UTC, Dalgona reviewed
asdf 파트에 `.tool-versions` 파일을 이용한 자동 버전 세팅 방법도 간단하게 언급하고 넘어가면 좋을 것 같네요 ㅎㅎ

2020-05-01 22:01 UTC, Dalgona commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +# asdf
https://github.com/elixir-korea/elixir-korea.github.io/pull/21#discussion_r362347138

```suggestion
## asdf
```

2020-05-01 22:01 UTC, Dalgona commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +# Elixir
https://github.com/elixir-korea/elixir-korea.github.io/pull/21#discussion_r362347138

2020-05-01 22:01 UTC, Dalgona commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +# VSCode
https://github.com/elixir-korea/elixir-korea.github.io/pull/21#discussion_r362347138

2020-05-02 22:46 UTC, Dalgona approved these changes
🥰

2020-05-03 01:58 UTC, chulkilee requested changes
:heart:

2020-05-03 01:58 UTC, chulkilee commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +    ElixirLS 가 버려지면서 fork 해서 진행되고 있는 프로젝트입니다.
얼마전 원저자와 정리가 되어서.. 원래 extension 써도 되긴 합니다.

https://elixirforum.com/t/introducing-elixirls-the-elixir-language-server/5857/93?u=chulkilee

아직 두 vscode extension 을 합치지는 않았습니다만 두 extension 이 같게 되었습니다.

2020-05-03 01:58 UTC, chulkilee commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +    Dash 는 language, framework 등의 document 를 통째로 다운받아 매우 빠르고 편하게 볼 수 있도록 해주는 프로그램입니다.
- document -> 문서 또는 documentation
- Dash 자체는 유료 프로그램이라는 점 명시해야할 듯 합니다

2020-05-03 01:58 UTC, chulkilee commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +$ brew install asdf
brew 로 설치하면 shell 자동으로 셋업해주나요? 그렇더라도 아마 shell 을 다시 열어야할 듯 합니다.

그 부분을 명시해주시고, [공식 설치 문서](https://asdf-vm.com/#/core-manage-asdf-vm) 링크로 달아주는 게 좋을 것 같습니다

git vs brew 뭐가 더 추천되는지는 모르겠네요.

2020-05-03 01:58 UTC, chulkilee commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +# 가장 최신인 22.3.2 를 설치해봅시다
가장 최신 => 글 쓴 시점에서 가장 최신

2020-05-03 01:58 UTC, chulkilee commented on posts/2020-04-25-how_to_setup_elixir_dev_env.md
> +$ brew install cmake
일단 elixir/erlang 에 직접 필요한 것만 넣는 게 나을 것 같습니다.

https://github.com/asdf-vm/asdf-erlang#osx

근데 사실 요거 테스트하기 어렵긴 하네요; 그냥 링크만 달아줘도 될 것 같고요

2020-05-11 22:28 UTC, chulkilee approved these changes

2020-05-11 23:26 UTC, kination approved these changes

2020-05-12 14:56 UTC, merged